import { useRef } from 'react'
import { useAppCoreState } from './core-state'
import { useAutoUpdateScheduler, useAppBehaviors } from './effects'
import { createAppControls } from './controls'
import { getSessionCommandState, getSettingsState } from './derived'
import { useAppKeyboard } from './keyboard'
import { useAppModalState } from './modal-state'
import { createAppRuntime } from './runtime'
import { createAppHandlers, handleKillSessionWithFeedback } from './handlers'
import { useAppStartup } from './state'
import { getConfigPath, saveConfig } from '../config'
import { getOpencodeSessionStats } from '../opencode'
import { resolveTheme } from '../styles/theme'
import { useTerminalSize } from '../util/terminal'
import { mark, measure } from '../util/perf'
import { getSettingEditorTitle, isOptionSetting } from '../settings'

export function useAppController() {
  const {
    appMode,
    setAppMode,
    viewMode,
    setViewMode,
    items,
    setItems,
    allItems,
    setAllItems,
    projectSourceItems,
    setProjectSourceItems,
    sessionCandidateItems,
    setSessionCandidateItems,
    sessionItems,
    setSessionItems,
    cursor,
    setCursor,
    agentCursor,
    setAgentCursor,
    searchQuery,
    setSearchQuery,
    message,
    setMessage,
    renameTarget,
    setRenameTarget,
    config,
    setConfig,
    backend,
    setBackend,
    pendingKillSessionName,
    setPendingKillSessionName,
    prefixActive,
    setPrefixActive,
    prefixTimeoutRef,
    textareaRef,
    lastSessionSelectionRef,
    lastProjectSelectionRef,
    toastMessage,
    setToastMessage,
    toastVisible,
    setToastVisible,
    updatedVersion,
    setUpdatedVersion,
  } = useAppCoreState()

  const {
    modalState,
    setModalState,
    modalInputValue,
    setModalInputValue,
    commandsCursor,
    setCommandsCursor,
    commandsSearchQuery,
    setCommandsSearchQuery,
    settingsCursor,
    setSettingsCursor,
    settingsSearchQuery,
    setSettingsSearchQuery,
    settingOptionsCursor,
    setSettingOptionsCursor,
    settingOptionsSearchQuery,
    setSettingOptionsSearchQuery,
    settingEditorValue,
    setSettingEditorValue,
    settingEditorError,
    setSettingEditorError,
    modalTextareaRef,
    commandsSearchTextareaRef,
    settingsSearchTextareaRef,
    settingOptionsSearchTextareaRef,
    settingEditorTextareaRef,
  } = useAppModalState()

  const { columns, rows } = useTerminalSize()
  const configPath = getConfigPath()
  const resolvedTheme = resolveTheme(config?.theme, config?.themes, config?.colorScheme)
  const theme = resolvedTheme.colors
  const { filteredSettingsEntries, filteredSettingOptions } = getSettingsState(
    config,
    modalState,
    settingsSearchQuery,
    settingOptionsSearchQuery
  )
  const hasScheduledAutoUpdateRef = useRef(false)

  useAppStartup(
    measure,
    lastSessionSelectionRef,
    lastProjectSelectionRef,
    mark,
    setConfig,
    setBackend,
    setMessage,
    setAppMode,
    setViewMode,
    setSessionItems,
    setProjectSourceItems,
    setAllItems,
    setItems,
    setCursor
  )

  useAutoUpdateScheduler(config, hasScheduledAutoUpdateRef)

  const { showMessage, refreshItems, loadOpencodeStatsForSession } = createAppRuntime({
    config,
    backend,
    viewMode,
    measure,
    lastSessionSelectionRef,
    lastProjectSelectionRef,
    setSessionItems,
    setProjectSourceItems,
    setAllItems,
    setItems,
    setCursor,
    setMessage,
    getOpencodeSessionStats,
  })

  const {
    regularSessions,
    agentSessions,
    selectedAgentSessionName,
    selectedPrimaryItem,
    filteredCommandEntries,
  } = getSessionCommandState(
    appMode,
    viewMode,
    items,
    cursor,
    agentCursor,
    config,
    commandsSearchQuery
  )

  const {
    clearPendingKill,
    requestKillSession,
    openRenameModal,
    openCommandsModal,
    openSettingsModal,
    openSettingOptions,
    openSettingEditor,
    closeModal,
  } = createAppControls({
    config,
    pendingKillSessionName,
    handleKillSession: item =>
      handleKillSessionWithFeedback(item, {
        backend,
        config,
        items,
        sessionItems,
        cursor,
        showMessage,
        refreshItems,
        setPendingKillSessionName,
      }),
    setPendingKillSessionName,
    setRenameTarget,
    setModalInputValue,
    setModalState,
    setCommandsSearchQuery,
    setCommandsCursor,
    setSettingEditorError,
    setSettingsSearchQuery,
    setSettingsCursor,
    setSettingOptionsSearchQuery,
    setSettingOptionsCursor,
    setSettingEditorValue,
  })

  const {
    handleKillSessionWrapper,
    handleSelectWrapper,
    handleLastSessionWrapper,
    handleRootSessionWrapper,
    handleEditTargetWrapper,
    handleRenameSubmit,
    handleNewSessionSubmit,
    handleSettingsEditorSubmit,
    handleSettingOptionSubmit,
    handleTogglePinnedSessionWrapper,
    executeCommand,
  } = createAppHandlers({
    backend,
    appMode,
    viewMode,
    config,
    items,
    sessionItems,
    cursor,
    showMessage,
    refreshItems,
    agentCursor,
    regularSessions,
    agentSessions,
    selectedPrimaryItem,
    sessionCandidateItems,
    projectSourceItems,
    closeModal,
    openRenameModal,
    openSettingsModal,
    requestKillSession,
    setAppMode,
    setViewMode,
    setAllItems,
    setItems,
    setCursor,
    setSearchQuery,
    setAgentCursor,
    setPendingKillSessionName,
    saveConfig,
    setConfig,
    setSettingEditorError,
    settingEditorValue,
    settingEditorPlainText: settingEditorTextareaRef.current?.plainText,
    renameTarget,
    renamedValue: (modalTextareaRef.current?.plainText ?? modalInputValue).trim(),
    searchTerm: searchQuery.trim(),
    loadOpencodeStatsForSession,
  })

  useAppKeyboard({
    appMode,
    viewMode,
    config,
    items,
    regularSessions,
    agentSessions,
    sessionItems,
    sessionCandidateItems,
    projectSourceItems,
    cursor,
    agentCursor,
    searchQuery,
    prefixActive,
    prefixTimeoutRef,
    modalState,
    filteredCommandEntries,
    commandsCursor,
    setCommandsCursor,
    filteredSettingsEntries,
    settingsCursor,
    setSettingsCursor,
    filteredSettingOptions,
    settingOptionsCursor,
    setSettingOptionsCursor,
    setModalState,
    setSettingEditorError,
    executeCommand,
    handleSettingOptionSubmit,
    handleSettingsEditorSubmit,
    handleRenameSubmit,
    handleNewSessionSubmit,
    isOptionSetting,
    openSettingOptions,
    openSettingEditor,
    closeModal,
    clearPendingKill,
    requestKillSession,
    togglePinnedSession: handleTogglePinnedSessionWrapper,
    openRenameModal,
    openCommandsModal,
    openSettingsModal,
    refreshItems,
    handleSelect: handleSelectWrapper,
    handleKillSession: handleKillSessionWrapper,
    handleLastSession: handleLastSessionWrapper,
    handleRootSession: handleRootSessionWrapper,
    handleEditTarget: handleEditTargetWrapper,
    loadOpencodeStatsForSession,
    setAppMode,
    setViewMode,
    setCursor,
    setAgentCursor,
    setSearchQuery,
    setAllItems,
    setItems,
    setPrefixActive,
    setMessage,
  })

  useAppBehaviors({
    appMode,
    viewMode,
    config,
    backend,
    sessionItems,
    projectSourceItems,
    sessionCandidateItems,
    lastSessionSelectionRef,
    lastProjectSelectionRef,
    setAllItems,
    setItems,
    setCursor,
    setSessionCandidateItems,
    filteredCommandEntriesLength: filteredCommandEntries.length,
    setCommandsCursor,
    commandsSearchQuery,
    filteredSettingsEntriesLength: filteredSettingsEntries.length,
    setSettingsCursor,
    filteredSettingOptionsLength: filteredSettingOptions.length,
    setSettingOptionsCursor,
    cursor,
    items,
    selectedPrimaryItem,
    pendingKillSessionName,
    agentSessions,
    agentCursor,
    regularSessions,
    setPendingKillSessionName,
    searchQuery,
    allItems,
    selectedAgentSessionName,
    loadOpencodeStatsForSession,
    setUpdatedVersion,
    setToastMessage,
    setToastVisible,
  })

  return {
    theme,
    resolvedTheme,
    columns,
    rows,
    screenProps: {
      theme,
      appMode,
      viewMode,
      config,
      backend,
      items,
      regularSessions,
      agentSessions,
      selectedPrimaryItem,
      cursor,
      agentCursor,
      searchQuery,
      prefixActive,
      pendingKillSessionName,
      projectCount: projectSourceItems.length,
      sessionItems,
      rows,
      columns,
      textareaRef,
      setSearchQuery,
      message,
      toastMessage,
      toastVisible,
      updatedVersion,
    },
    modalProps: {
      modalState,
      columns,
      rows,
      configPath,
      themeId: resolvedTheme.id,
      themeName: resolvedTheme.name,
      colorMode: resolvedTheme.mode,
      filteredCommandEntries,
      commandsCursor,
      commandsSearchQuery,
      setCommandsCursor,
      setCommandsSearchQuery,
      filteredSettingsEntries,
      settingsCursor,
      settingsSearchQuery,
      setSettingsCursor,
      setSettingsSearchQuery,
      filteredSettingOptions,
      settingOptionsCursor,
      settingOptionsSearchQuery,
      setSettingOptionsCursor,
      setSettingOptionsSearchQuery,
      settingEditorValue,
      settingEditorError,
      setSettingEditorValue,
      modalInputValue,
      setModalInputValue,
      commandsSearchTextareaRef,
      settingsSearchTextareaRef,
      settingOptionsSearchTextareaRef,
      settingEditorTextareaRef,
      modalTextareaRef,
      getSettingEditorTitle,
    },
  }
}
